import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { PrismaClient } from '@prisma/client'
import Link from "next/link";

export async function getStaticProps() {
  const prisma = new PrismaClient()
  const posts = await prisma.post.findMany()
  return {
    props : { posts }
  }
}

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Wansport</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://wansport.com/">Wansport!</a>
        </h1>

        <p className={styles.description}>
          Get started
        </p>

        <div className={styles.grid}>
          <Link href="/auth/register">
            <a className={styles.card}>
                <h2>Registra &rarr;</h2>
                <p>Crea il tuo account per poi effettuare l&apos;accesso</p>
            </a>
          </Link>

          <Link href="/auth/login">
            <a className={styles.card}>
              <h2>Accedi &rarr;</h2>
              <p>Inserisci le credenziali e accedi alla piattaforma</p>
            </a>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
