import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Wansport</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://wansport.com/">Wansport!</a>
        </h1>

        <p className={styles.description}>
          Get started
        </p>

        <div className={styles.grid}>
          <Link href="/auth/register">
            <a className={styles.card}>
                <h2>Registra &rarr;</h2>
                <p>Crea il tuo account per poi effettuare l&apos;accesso</p>
            </a>
          </Link>

          <Link href="/auth/login">
            <a className={styles.card}>
              <h2>Accedi &rarr;</h2>
              <p>Inserisci le credenziali e accedi alla piattaforma</p>
            </a>
          </Link>
        </div>
      </main>
    </div>
  )
}

export default Home
